const TO_DEVICE_CHANNEL_ID_STR         = "2620673";
const TO_DEVICE_CHANNEL_READ_API_KEY   = "WRGUSK6I48UT6E7J";
const TO_DEVICE_CHANNEL_WRITE_API_KEY  = "WNB5I6TWLZ3O2AM3";
const FROM_DEVICE_CHANNEL_ID_STR       = "2620807";
const FROM_DEVICE_CHANNEL_READ_API_KEY = "TAVWKJZB8KP380BW";
